### ISSUE TITLE
Most icons disappear when clicked on

### ISSUE THREAD

**Issue by masuteri** [kuba2k2/spicetify-beat-saber#11]
Icons indicating that the app is unsure if the song exists and that it doesn't exist will disappear when clicked on to bring up the search and then exiting it. Songs that are verified will also turn white. When hovering over disappeared icons, the icon showing up will be an X.
![kuva](https://github.com/kuba2k2/spicetify-beat-saber/assets/80328342/ec4e0dfe-9fc3-4895-8e51-70514b28dd58)

**Comment by masuteri** [comment]
I did not realize how the app worked at first. My bad

**Comment by kuba2k2** [comment]
This is expected behavior. Colored icons are there to indicate newly found (or not found) songs. The X and ? icons disappear after viewing to make it clear that the songs are not available, instead of cluttering the UI with unnecessary icons.
