### ISSUE TITLE
Trouble Understanding Backend Configuration

### ISSUE THREAD

**Issue by Razwerkz** [kuba2k2/spicetify-beat-saber#4]
I am having trouble getting the backend configured for download functionality.  What am I supposed to put for the host and port?

**Comment by kuba2k2** [comment]
You don't need to change it, the defaults are just fine. In the Spotify app, enter `127.0.0.1:23287` in the hostname field, as shown on the screenshot.

**Comment by Razwerkz** [comment]
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/9700289/21002cee-e8ea-4a16-97a7-28f5140aa313)
I get this error when trying to download.  I had figured I had the configuration incorrect...

**Comment by kuba2k2** [comment]
Did you set the beat saber directory correctly?

**Comment by Razwerkz** [comment]
Yes.  Just double-checked.

**Comment by kuba2k2** [comment]
Well, then post the .env file here so I can see what's wrong. Also post a screenshot of the settings pop-up in Spotify. Most likely the authentication parameter is wrong.

**Comment by Razwerkz** [comment]
[Text version of `.beatsaber.env`](https://github.com/kuba2k2/spicetify-beat-saber/files/12178698/beatsaber.txt)
(file was renamed so that GitHub would accept it)

Sorry for the delay.

**Comment by kuba2k2** [comment]
You don't need to change AUTH_USERNAME and AUTH_PASSWORD, leave the defaults. Otherwise it will fail with an authentication error if you don't configure it properly. The username and password are only used locally and don't mean anything.

**Comment by Razwerkz** [comment]
I'm also getting this when the backend attempts to initialize:
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/9700289/80774e63-8094-4ac3-8c56-a28dcda176e3)

**Comment by kuba2k2** [comment]
Well, in this case you didn't put the `.beatsaber.env` file in the `.spicetify` directory. If the directory doesn't exist, create it and place the file there.

**Comment by Razwerkz** [comment]
I did, but maybe it's not the correct one.  I have one in the
`AppData/Local/spicetify` and `AppData/Roaming/spicetify` directories.  Is
there another?

**Comment by kuba2k2** [comment]
Yes, the directory is called `.spicetify` (note the dot in front) and is placed in your user folder (one level higher than AppData.

**Comment by kuba2k2** [comment]
I've just released version 2.1.0, which doesn't require any configuration steps in .env files.

Uninstall the backend and install the new version (2.0.1) first.

Then update the Spicetify extension to 2.1.0.

Then open the settings popup, click the three dots icon and browse to your Beat Saber directory:
![obraz](https://github.com/kuba2k2/spicetify-beat-saber/assets/30433568/98ef0308-3a14-4a9e-a58d-f1992db22cf3)

**Comment by Razwerkz** [comment]
I've removed the old backend, and installed the new one.  I've also installed the new plugin version.

I'm setting the Hostname field in the in-app configuration as directed, but now it can't seem to connect to the backend.

![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/9700289/7221705a-99d5-4ed3-a5b3-3e76c25d1ab6)

It won't let me enter anything in the directory field, probably because of the backend error.

**Comment by kuba2k2** [comment]
Thanks, this should be fixed in extension v2.1.1 and backend v2.0.2.

**Comment by Razwerkz** [comment]
I was able to update both.

The UI now shows all is well, but when a download is attempted, the same "Error: Couldn't connect to backend" toast appears.

![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/9700289/96719a44-9ea0-4c7d-98eb-51250dcbc2de)

**Comment by kuba2k2** [comment]
Is the backend running and showing as connected on the UI? Did you reboot your PC after installing backend?

**Comment by kuba2k2** [comment]
You might not have enough permissions for the ProgramFiles folder. It's best to install BeatSaber in a different Steam library, such as on C:\ or somewhere else. Otherwise you can assign permissions to the BS directory using the windows "Properties" sheet.

**Comment by Razwerkz** [comment]
Backend is confirmed (via Process Explorer) to be running, and the UI shows as "Connected: v2.0.2," as shown in the above screenshot.  Permissions shouldn't be an issue, but I tried setting "Everyone" to have Full Control access anyway, just to see if it would change anything.  Unfortunately, no dice.

**Comment by kuba2k2** [comment]
Open your browser and go to `http://localhost:23287/levels/download/1591e1210ddb60bfe5ad2434359246ee7e888c1f` (the hash is the level ID, first one I had at hand). Post a screenshot of the output.

**Comment by Razwerkz** [comment]
Sorry, it's been a busy week.

A text output is displayed, and nothing more:

```
{"levelDir":"b0b5 (Paranoid - ggdruber)","hash":"1591e1210ddb60bfe5ad2434359246ee7e888c1f","name":"Paranoid","subName":"","authorName":"Black Sabbath","mapperName":"ggdruber","characteristics":{"Standard":["Expert","ExpertPlus"]},"songFilename":"song.egg","coverFilename":"cover.jpg"}
```

**Comment by Razwerkz** [comment]
I decided to try it again today.  I remembered that I had switched the queue block on for a while after troubleshooting with it, so I turned the block off and tried to download the next available track in my queue, which so happened to be Wintergatan's "Marble Machine."

Huh.  It downloaded the song with no errors.

**Comment by kuba2k2** [comment]
Haha, I'm glad that worked. The JSON you posted today would indicate that no errors occur. Maybe it was just a temporary problem.
