### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by EliasRonefors** [kuba2k2/spicetify-beat-saber#5]
Due to technical issues I decided to uninstall but I couldn't figure out how. Instead I restored my previous backup of Spicetify but the Beat Saber tab is still left in the Spotify sidebar, it's there but it is broken. How do I fix this?

**Comment by kuba2k2** [comment]
If you ran `spicetify restore` and it's still there, that might mean your backups were made after installing the addon. It would be easiest to reinstall Spotify completely, and then run `spicetify backup` and `spicetify apply` to install all other addons.

**Comment by Sooperfish** [comment]
1. Run `spicetify config-dir` to open the spicetify folder
2. Go to the `CustomApps` folder
3. Delete the `beatsaber` folder

Then, run the following commands:

```
spicetify config custom_apps beatsaber-
spicetify apply
```
