### ISSUE TITLE
Api not working

### ISSUE THREAD

**Issue by Mystrik** [kuba2k2/spicetify-beat-saber#7]
Assuming it's because I'm not logged in with beastsaber, but my account is a discord logged in account and I cant login that way through the app, and creating beastsaber accounts is impossible as the site is no longer maintained, is there any way to fix this or make the api look through beatsaver instead [(BeatSaver API)](https://api.beatsaver.com/docs/index.html?url=./swagger.json)

![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/38515916/94acdc04-99a8-4d42-aeee-d9cbb7e37320)
(infinitely loading searching for existing song)
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/38515916/61faf2f1-ed8c-416d-ba1e-462e88b52f7b)

**Comment by kuba2k2** [comment]
BeastSaber account is only used for bookmarking, it's not needed for the core features of searching and downloading maps (this is done via BeatSaver).

Make sure to *uncheck* "Block queue" in the options window.
![obraz](https://github.com/kuba2k2/spicetify-beat-saber/assets/30433568/761548e0-8a74-4454-992a-c79e845a8206)

**Comment by Mystrik** [comment]
Oh guess I missed that lol, thanks so much!
